version: "3.2"

services:
  traefik:
    image: traefik
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  webui-homepage:
    build:
      context: context/webui/
    expose:
      - "8088"
    volumes:
      -  $PWD/applications/homepage/public:/public:ro
    labels:
      - "traefik.frontend.rule=Host:webui.docker.localhost"
      - "traefik.port=8088"
  portainer:
    image: portainer/portainer
    expose:
      - "9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      -  portainer_data:/data
    labels:
      - "traefik.frontend.rule=Host:portainer.docker.localhost"
      - "traefik.port=9000"

volumes:
  portainer_data:
