version: 2

defaults: &defaults
  working_directory: /tmp/workspace

use_node8: &use_node8
  docker:
    - image: circleci/node:8

jobs:
  job_tests:
    <<: *defaults
    <<: *use_node8
    steps:
      - checkout

workflows:
  version: 2
  tests:
    jobs:
      - job_tests
