version: 2

use_node8: &use_node8
  docker:
    - image: circleci/node:8

jobs:
  homepage_tester:
    <<: *use_node8
    steps:
      - checkout
      - run: cd applications/homepage && yarn
      - run: cd applications/homepage && yarn test
  homepage_builder:
    <<: *use_node8
    steps:
      - checkout
      - run: cd applications/homepage && yarn
      - run: cd applications/homepage && yarn build
  homepage_packager:
    steps:
      - checkout
      - setup_remote_docker
      - run: cd applications/homepage && docker build -t faas-homepage .
      - run: docker image ls

workflows:
  version: 2
  homepage:
    jobs:
      - homepage_tester:
          filters:
            branches:
              only: master
      - homepage_builder:
          requires:
            - homepage_tester
      - homepage_packager:
          requires:
            - homepage_builder
