version: 2

use_node8: &use_node8
  docker:
    - image: circleci/node:8

jobs:
  homepage_test:
    <<: *use_node8
    steps:
      - checkout
      - run: cd applications/homepage && yarn
      - run: cd applications/homepage && yarn test
  homepage_build:
    <<: *use_node8
    steps:
      - checkout
      - run: cd applications/homepage && yarn
      - run: cd applications/homepage && yarn build

workflows:
  version: 2
  homepage:
    jobs:
      - homepage_test:
          filters:
            branches:
              only: master
      - homepage_build:
          requires:
            - homepage_test
