version: 2

use_machine: &use_machine
  machine: true
use_node8: &use_node8
  docker:
    - image: circleci/node:8

jobs:

  # webui-homepage
  homepage_tester:
    <<: *use_node8
    steps:
      - checkout
      - run: cd applications/homepage && yarn
      - run: cd applications/homepage && yarn test
  homepage_builder:
    <<: *use_node8
    steps:
      - checkout
      - run: cd applications/homepage && yarn
      - run: cd applications/homepage && yarn build
  homepage_packager:
    <<: *use_machine
    steps:
      - checkout
      - run: cd applications/homepage && docker build -t faas-homepage .

  # webui-company
  company_tester:
    <<: *use_node8
    steps:
      - checkout
      - run: cd applications/company && yarn
      - run: cd applications/company && yarn test
  company_builder:
    <<: *use_node8
    steps:
      - checkout
      - run: cd applications/company && yarn
      - run: cd applications/company && yarn build
  company_packager:
    <<: *use_machine
    steps:
      - checkout
      - run: cd applications/company && docker build -t faas-homepage .

workflows:
  version: 2
  homepage:
    jobs:
      - homepage_tester:
          filters:
            branches:
              only: master
      - homepage_builder:
          requires:
            - homepage_tester
      - homepage_packager:
          requires:
            - homepage_builder
  company:
    jobs:
      - company_tester:
          filters:
            branches:
              only: master
      - company_builder:
          requires:
            - company_tester
      - company_packager:
          requires:
            - company_builder
