version: 2

use_defaults: &use_defaults
  working_directory: /tmp/workspace

use_node8: &use_node8
  docker:
    - image: circleci/node:8

jobs:
  homepage:
    <<: *use_defaults
    <<: *use_node8
    steps:
      - checkout
      - run: cd applications/homepage
      - run: yarn
      - run: yarn test
      - run: yarn build

workflows:
  version: 2
  build:
    jobs:
      - homepage
