version: 2

use_defaults: &use_defaults
  working_directory: /tmp/workspace

use_node8: &use_node8
  docker:
    - image: circleci/node:8

jobs:
  homepage_test:
    <<: *use_defaults
    <<: *use_node8
    steps:
      - checkout
      - run: echo $PWD
      - run: ls -l
  homepage_build:
    <<: *use_defaults
    <<: *use_node8
    steps:
      - checkout
      - run:
          name: "build"
          command: |
            cd applications/homepage
            yarn
            yarn build

workflows:
  version: 2
  homepage:
    jobs:
      - homepage_test:
          filters:
            branches:
              only: master
      - homepage_build:
          requires:
            - homepage_test
